version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install dependencies needed for running tests
      - echo Installing source NPM dependencies...
      - npm ci
  build:
    commands:
      - echo Entered the build phase...
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
